platform :ios, '9.0'
use_frameworks!

target 'TVShows' do
	pod 'Alamofire'
	pod 'CodableAlamofire'
	pod 'SVProgressHUD'
	pod 'PromiseKit/CorePromise', '~> 6.0'
	pod 'PromiseKit/Alamofire'
  pod 'Kingfisher', '~> 4.2'
  pod 'KeychainSwift'
  pod 'SkyFloatingLabelTextField', '~> 3.0'

end
